### ISSUE TITLE
FDB $ not compiling correctly

### ISSUE THREAD

**Issue by Marky-D-32** [jimbro1000/online6809#31]
FDB $0400 or FDB $400 comiiles to 0000
However, FDB 1024 compiles correctly to 0400

**Comment by jimbro1000** [comment]
Bug confirmed

**Comment by jimbro1000** [comment]
Error is from assembler.js line 504 - code assumes that all data is decimal. The code simply uses parseInt to turn text into an integer but this cannot handle hexadecimal without a little extra work
