### ISSUE TITLE
JMP [,Y++]

### ISSUE THREAD

**Issue by adumont** [jimbro1000/online6809#5]
`JMP [,Y++]` doesn't post-increment `Y`.

**Comment by jimbro1000** [comment]
Confirmed, indexed addressing on JMP misses post increment step

**Comment by jimbro1000** [comment]
Confirmed fixed

**Comment by adumont** [comment]
Is the indirect addressing function not factored out of each instructions?
(I mean, fixing it for one instructions should hopefully fix it for all of
them). Having it distributed in all the instruction is prone to this kind
of bug. Furthermore it would help a lot to find bugs, because maybe you
find it in LDx but never in JMP or LEAx.
